/**
 * Type definition for available guild setting names. This should be updated if
 * settings are added or removed.
 */
export type Settings =
  | "levels"
  | "welcome_channel"
  | "depart_channel"
  | "level_channel"
  | "suggestion_channel"
  | "custom_welcome"
  | "hearts"
  | "blocked"
  | "automod_channels"
  | "no_automod_channels"
  | "automod_roles"
  | "allowed_links"
  | "link_message"
  | "level_roles"
  | "join_role"
  | "leave_message"
  | "report_channel"
  | "level_ignore"
  | "sass_mode"
  | "message_events"
  | "voice_events"
  | "thread_events"
  | "moderation_events"
  | "member_events"
  | "links"
  | "profanity"
  | "profanity_message"
  | "emote_channels"
  | "appeal_link"
  | "antiphish"
  | "initial_xp"
  | "level_style"
  | "level_message"
  | "role_message"
  | "triggers"
  | "welcome_style"
  | "ticket_category"
  | "ticket_log_channel"
  | "ticket_role";
