import { PermissionFlagsBits } from "discord.js";

import { Settings } from "../../interfaces/settings/Settings";

export const SettingsPermissions: {
  [key in Settings]: (keyof typeof PermissionFlagsBits)[] | null;
} = {
  levels: null,
  welcome_channel: ["ViewChannel", "SendMessages", "EmbedLinks"],
  depart_channel: ["ViewChannel", "SendMessages", "EmbedLinks"],
  level_channel: ["ViewChannel", "SendMessages", "EmbedLinks"],
  suggestion_channel: ["ViewChannel", "SendMessages", "EmbedLinks"],
  custom_welcome: null,
  hearts: null,
  blocked: null,
  automod_channels: ["ManageMessages"],
  no_automod_channels: null,
  automod_roles: null,
  allowed_links: null,
  link_message: null,
  level_roles: ["ManageRoles"],
  join_role: ["ManageRoles"],
  leave_message: null,
  report_channel: ["ViewChannel", "SendMessages", "EmbedLinks"],
  level_ignore: null,
  sass_mode: null,
  message_events: ["ViewChannel", "SendMessages", "EmbedLinks"],
  voice_events: ["ViewChannel", "SendMessages", "EmbedLinks"],
  thread_events: ["ViewChannel", "SendMessages", "EmbedLinks"],
  moderation_events: ["ViewChannel", "SendMessages", "EmbedLinks"],
  member_events: ["ViewChannel", "SendMessages", "EmbedLinks"],
  links: null,
  profanity: null,
  profanity_message: null,
  emote_channels: ["ManageMessages"],
  appeal_link: null,
  antiphish: null,
  initial_xp: null,
  level_style: null,
  level_message: null,
  role_message: null,
  new_triggers: null,
  welcome_style: null,
  ticket_category: ["ManageChannels"],
  ticket_log_channel: ["ViewChannel", "SendMessages", "EmbedLinks"],
  ticket_role: null,
  starboard_emote: null,
  starboard_channel: ["ViewChannel", "SendMessages", "EmbedLinks"],
  starboard_threshold: null,
  level_decay: null,
};
