"project_id": "496131"
"api_token_env": CROWDIN_PERSONAL_TOKEN
"base_url": "https://api.crowdin.com"
"base_path": "."
"preserve_heirarchy": false

"files":
  [
    {
      "source": "/src/config/i18n/en-GB/**.json",
      "translation": "/src/config/i18n/%two_letters_code%/%original_file_name%",
    },
  ]
